name: Build HTML Documentation

on:
  push:
    branches:
      - feat/html-build
  pull_request:
    branches:
      - feat/html-build

jobs:
  build-html:
    runs-on: ubuntu-24.04
    if: github.repository == 'matjam/mega65-user-guide'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Cache apt packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-apt-
          
    - name: Cache PDF build
      uses: actions/cache@v4
      with:
        path: |
          mega65-book.pdf
          mega65-book.aux
          mega65-book.bbl
          mega65-book.blg
          mega65-book.fdb_latexmk
          mega65-book.fls
          mega65-book.idx
          mega65-book.ilg
          mega65-book.ind
          mega65-book.listing
          mega65-book.log
          mega65-book.out
          mega65-book.toc
          mega65-book.xref
          mega65-book.4ct
          mega65-book.4tc
          styleguide.pdf
          styleguide.aux
          styleguide.fdb_latexmk
          styleguide.fls
          styleguide.idx
          styleguide.ilg
          styleguide.ind
          styleguide.listing
          styleguide.log
          styleguide.out
          styleguide.toc
          styleguide.xref
          styleguide.4ct
          styleguide.4tc
          styleguide-html.log
          api-conio.tex
          appendix-basic65-condensed.tex
          appendix-basic65-indexed.tex
          appendix-kernal-jumptable.aux
          document-memory
          examples/iec-data-logger-2.tex
          examples/iec-data-logger-2.txt
          examples/iec-data-logger.tex
          examples/iec-data-logger.txt
          examples/ledcycle.tex
          examples/ledcycle.txt
          generate_condensed
          gitinfo.tex
          index_basic_programmes
          instruction_set
          instructionset-4510.tex
          instructionset-45GS02.tex
          instructionset-6502.tex
          keymap
          keymap_table_1.tex
          keymap_table_2.tex
          keymap_table_3.tex
          keymap_table_4.tex
          keymap_table_5.tex
          libc-doc
          opcodetable-4510.tex
          opcodetable-6502.tex
          prg2tex
          regtable_*.tex
          unicode_mapping.tex
        key: ${{ runner.os }}-pdf-${{ hashFiles('**/*.tex', '**/references.bib', '**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-pdf-
          
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ca-certificates git make build-essential pkg-config gcc g++ \
          libssl-dev libhpdf-dev \
          ghostscript inkscape imagemagick \
          latexmk texlive-full \
          pandoc \
          python3 python3-fonttools woff2 fontforge python3-fontforge
        
    - name: Build PDF
      run: |
        if [ ! -f mega65-book.pdf ]; then
          echo "PDF not found in cache, building..."
          make mega65-book.pdf
        else
          echo "PDF found in cache, skipping build"
        fi
      
    - name: Build HTML
      run: make mega65-book-html
      
    - name: Upload HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mega65-book-html
        path: html/mega65-book/
        retention-days: 30
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: mega65-book-pdf
        path: mega65-book.pdf
        retention-days: 30
        
    - name: Deploy HTML to S3
      if: github.ref == 'refs/heads/feat/html-build'
      run: |
        # Install AWS CLI
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        
        # Sync HTML files to S3
        aws s3 sync html/mega65-book/ s3://${{ secrets.S3_BUCKET_NAME }}/mega65-book/ --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        
    - name: Invalidate CloudFront Cache (Distribution 1)
      if: github.ref == 'refs/heads/feat/html-build'
      uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: "/mega65-book/*"
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: E3CBXE5UNLO2XX
        
    - name: Invalidate CloudFront Cache (Distribution 2)
      if: github.ref == 'refs/heads/feat/html-build'
      uses: awact/cloudfront-action@master
      env:
        SOURCE_PATH: "/mega65-book/*"
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION_ID: E2N2NU6EOMTCJY
