name: Build HTML Documentation

on:
  push:
    branches:
      - feat/html-build
  pull_request:
    branches:
      - feat/html-build

jobs:
  build-html:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ca-certificates git make build-essential pkg-config gcc g++ \
          libssl-dev libhpdf-dev \
          ghostscript inkscape imagemagick \
          latexmk texlive-full \
          pandoc \
          python3 python3-fonttools woff2 fontforge python3-fontforge
        
    - name: Build PDF
      run: make mega65-book.pdf
      
    - name: Build HTML
      run: make mega65-book-html
      
    - name: Upload HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mega65-book-html
        path: html/mega65-book/
        retention-days: 30
        
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: mega65-book-pdf
        path: mega65-book.pdf
        retention-days: 30
